version: '3'

services:

  consul-server-1:
    container_name: consul-server-1
    hostname: consul-server-1
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      consul_net:
        ipv4_address: 172.22.0.3
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bind=172.22.0.3 -client 0.0.0.0 --bootstrap-expect=3 -ui -node=consul-server-1"

  consul-server-2:
    container_name: consul-server-2
    hostname: consul-server-2
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      consul_net:
        ipv4_address: 172.22.0.4
    ports:
      - "9300:8300"
      - "9301:8301"
      - "9301:8301/udp"
      - "9302:8302"
      - "9302:8302/udp"      
      - "9400:8400"
      - "9500:8500"
      - "9600:8600"
    command: "agent -server -client 0.0.0.0 -retry-join 172.22.0.3  -node=consul-server-2"

  consul-server-3:
    container_name: consul-server-3
    hostname: consul-server-3
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      consul_net:
        ipv4_address: 172.22.0.5
    ports:
      - "10300:8300"
      - "10301:8301"
      - "10301:8301/udp"
      - "10302:8302"
      - "10302:8302/udp"
      - "10400:8400"
      - "10500:8500"
      - "10600:8600"
    command: "agent -server -client 0.0.0.0 -retry-join 172.22.0.3  -node=consul-server-3"

  consul-agent-1: 
    container_name: consul-agent-1
    hostname: consul-agent-1
    image: consul:latest
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
    networks:
      consul_net:
        ipv4_address: 172.22.0.6
    ports:
      - "11300:8300"
      - "11301:8301"
      - "11301:8301/udp"
      - "11302:8302"
      - "11302:8302/udp"
      - "11400:8400"
      - "11500:8500"
      - "11600:8600"
    command: "agent -client 0.0.0.0 -retry-join 172.22.0.3 -node=consul-agent-1"

  fabio:
    container_name: fabio-server
    hostname: fabio-server
    image: fabiolb/fabio
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      consul_net:
        ipv4_address: 172.22.0.10
    ports:
      - "9998:9998"
      - "9999:9999"
    volumes:
      - ./fabio.properties:/etc/fabio/fabio.properties

networks:
  consul_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
