FROM centos:7
RUN yum install -y epel-release \
    && yum -y update \
    && yum -y install vim \
    &&  yum -y install zip \
    &&  yum -y install unzip \ 
    &&  yum -y install lrzsz \
    &&  yum -y install libunwind \
    &&  yum clean all

