FROM centos:7
LABEL Author="kevinyeti" 
RUN yum install -y epel-release \
    && yum -y update \
    && yum -y install vim \
    &&  yum -y install zip \
    &&  yum -y install unzip \ 
    &&  yum -y install lrzsz \
    &&  yum clean all

